# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0030_auto_20171105_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityextraratings',
            name='how_can_we_improve_survey',
            field=models.TextField(blank=True),
        ),
    ]
