# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 18:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0031_auto_20171111_1740'),
        ('Community', '0031_merge_20171112_1044'),
    ]

    operations = [
    ]
