# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 22:42
from __future__ import unicode_literals

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0032_merge_20171112_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityinst',
            name='photo',
            field=s3direct.fields.S3DirectField(default=None),
        ),
    ]
