# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-12-03 15:37
from __future__ import unicode_literals

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0010_studentprojects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senateprojects',
            name='image',
            field=s3direct.fields.S3DirectField(blank=True, null=True),
        ),
    ]
